### ISSUE TITLE
Possible issue modifying properties in certain structs

### ISSUE THREAD

**Issue by d-geula** [dmcooller/S2ZonaConfigurator#2]
I think I may have found another edge case. I tried my best to rule myself out but I am kind of out of my depth here so again it could be my lack of understanding.

Basically, while trying to auto convert the mod "Better NPC Progressive Loadouts" (it was a my stress test mod since it seems pretty complex) I ran into this issue:
```
 fail: S2ZonaConfigurator.Services.ModService.ConfigParser[0]
      Error modifying value for path: GeneralNPC_Neutral_Stormtrooper_ItemGenerator -> ItemGenerator -> [*] -> PlayerRank
      System.Collections.Generic.KeyNotFoundException: Failed to find the target line PlayerRank
         at S2ZonaConfigurator.Services.ModService.ConfigParser.FindValueLine(Int32 startIdx, Int32 endIdx, String key) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 354
         at S2ZonaConfigurator.Services.ModService.ConfigParser.ModifyValue(List`1 pathComponents, Object newValue) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 367
fail: S2ZonaConfigurator.Services.ModService.ConfigParser[0]
      Error applying action Modify to GeneralNPC_Neutral_Stormtrooper_ItemGenerator::ItemGenerator::[*]::PlayerRank
      System.Collections.Generic.KeyNotFoundException: Failed to find the target line PlayerRank
         at S2ZonaConfigurator.Services.ModService.ConfigParser.FindValueLine(Int32 startIdx, Int32 endIdx, String key) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 354
         at S2ZonaConfigurator.Services.ModService.ConfigParser.ModifyValue(List`1 pathComponents, Object newValue) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 367
         at S2ZonaConfigurator.Services.ModService.ConfigParser.ApplyAction(ConfigAction action) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 270
║
║ Status: Failed to process
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════
fail: S2ZonaConfigurator.Services.ModService.ModProcessor[0]
      Error processing mod mods\Better NPC Progressive Loudouts Test.json
      System.Collections.Generic.KeyNotFoundException: Failed to find the target line PlayerRank
         at S2ZonaConfigurator.Services.ModService.ConfigParser.FindValueLine(Int32 startIdx, Int32 endIdx, String key) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 354
         at S2ZonaConfigurator.Services.ModService.ConfigParser.ModifyValue(List`1 pathComponents, Object newValue) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 367
         at S2ZonaConfigurator.Services.ModService.ConfigParser.ApplyAction(ConfigAction action) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ConfigParser.cs:line 270
         at S2ZonaConfigurator.Services.ModService.ModProcessor.ProcessMod(String modFile, ModData modData) in D:\Coding\MyOwnProjects\S2ZonaConfigurator\S2ZonaConfigurator\Services\ModService\ModProcessor.cs:line 39
```
It seems like if I try to modify a property in that type of struct your tool will attempt to modify the first instance of the struct `[*]` it finds (in `ItemGenerator`) but since there are loads of identical paths like and I don't think you made a way to specify one of them it fails as that particular instance doesn't contain that property.

I tried to find a hacky solution just out interest by also "modifying" the `Category` property (keeping default value) as a sort of index but it either doesn't work or, more likely, I wasn't able to figure it out.

Here's the struct that the action that failed was trying to modify in `DynamicItemGenerator.cfg` (vanilla):

Here's the action for reference:
```
{
    "type": "Modify",
    "file": "Stalker2/Content/GameLite/GameData/ItemGeneratorPrototypes/DynamicItemGenerator.cfg",
    "path": "GeneralNPC_Neutral_Stormtrooper_ItemGenerator::ItemGenerator::[*]::PlayerRank",
    "value": "ERank::Master",
    "defaultValue": "ERank::Newbie, ERank::Experienced"
}
```
As far as I can tell the value(s) are actually not correct as this issue seems to have affected me as well but I think it still applies because if this were the actual modification it wouldn't work either.

Let me know if you need more info, assuming this isn't a me problem. I'm too tired and confused now to think of anything else lol.

**Comment by dmcooller** [comment]
I guess the `[*]` struct breaks the logic. I will look into it

**Comment by dmcooller** [comment]
Fixed that issue in new [release](https://github.com/dmcooller/S2ZonaConfigurator/releases/tag/ver_0.0.5). We can't distinguish those structures by name so it should be indexed with a number in the `path`. The count starts from 0. I have tried the following actions and it worked:

```json
    {
      "type": "Modify",
      "file": "Stalker2/Content/GameLite/GameData/ItemGeneratorPrototypes/DynamicItemGenerator.cfg",
      "path": "GeneralNPC_Consumables::ItemGenerator::[*]:1::PossibleItems::[3]::MinCount",
      "value": "22",
      "defaultValue": "1"
    },
    {
      "type": "Modify",
      "file": "Stalker2/Content/GameLite/GameData/ItemGeneratorPrototypes/DynamicItemGenerator.cfg",
      "path": "GeneralNPC_Neutral_Stormtrooper_ItemGenerator::ItemGenerator::[*]:9::PlayerRank",
      "value": "ERank::Master",
      "defaultValue": "ERank::Newbie, ERank::Experienced"
    },
    {
      "type": "Modify",
      "file": "Stalker2/Content/GameLite/GameData/ItemGeneratorPrototypes/DynamicItemGenerator.cfg",
      "path": "GeneralNPC_Neutral_Stormtrooper_ItemGenerator::ItemGenerator::[*]:1::PossibleItems::[*]:0::MinDurability",
      "value": "14",
      "defaultValue": "0.25"
    }
```

Also there is a diff report feature now so that may help you a bit.

**Comment by d-geula** [comment]
Wow, that was quick. I'll need to sort out my script to handle this so I can test it but I'm sure it's great.

Apologies for disturbing your christmas/holiday, and speaking of which, have a good one.

**Comment by dmcooller** [comment]
No worries, happy holidays to you too!
